[project]
name = "local-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shmach", email = "mmachado0222@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "course-parser",
    "fastapi[standard]>=0.141.1",
    "python-dotenv>=1.0.1",
]

[project.scripts]
local-server = "local_server:main"
export-openapi = "local_server.export_openapi:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
course-parser = { workspace = true }
