/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/vault/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content Path */
        get: operations["get_vault_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course By Slug */
        get: operations["get_course"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}/lessons/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson By Topic */
        get: operations["get_lesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}/exercises/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise By Topic */
        get: operations["get_exercise_set"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Attempt */
        Attempt: {
            /** Course */
            course: string;
            /** Topic */
            topic: string;
            /** Attempt */
            attempt: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Score */
            score: string;
            /**
             * Result
             * @enum {string}
             */
            result: "good" | "mixed" | "weak";
            /**
             * Weak Points
             * @default []
             */
            weak_points: string[];
            /** Content */
            content: string;
        };
        /** Course */
        Course: {
            /** Course */
            course: string;
            /** Slug */
            slug: string;
            /**
             * Created
             * Format: date
             */
            created: string;
            /**
             * Depth
             * @enum {string}
             */
            depth: "quick" | "standard" | "deep";
            /** Level */
            level: string;
            /** Goal */
            goal: string;
            /** Language */
            language: string;
            /** Overview */
            overview: string;
            /** Modules */
            modules: components["schemas"]["Module"][];
        };
        /**
         * CourseBundle
         * @description Everything the vault holds for one course: curriculum plus generated content.
         */
        CourseBundle: {
            course: components["schemas"]["Course"];
            /**
             * Lessons
             * @default []
             */
            lessons: components["schemas"]["Lesson"][];
            /**
             * Exercise Sets
             * @default []
             */
            exercise_sets: components["schemas"]["ExerciseSet"][];
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["Attempt"][];
        };
        /** ExerciseSet */
        ExerciseSet: {
            /** Course */
            course: string;
            /** Topic */
            topic: string;
            /**
             * Generated
             * Format: date
             */
            generated: string;
            /** Difficulty Target */
            difficulty_target: number;
            /** Content */
            content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Lesson */
        Lesson: {
            /** Course */
            course: string;
            /** Topic */
            topic: string;
            /** Title */
            title: string;
            /**
             * Generated
             * Format: date
             */
            generated: string;
            /** Covers */
            covers: string[];
            /** Content */
            content: string;
        };
        /** Module */
        Module: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Topics */
            topics: components["schemas"]["Topic"][];
        };
        /** Subtopic */
        Subtopic: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /** Topic */
        Topic: {
            meta: components["schemas"]["TopicMeta"];
            /** Title */
            title: string;
            /** Subtopics */
            subtopics: components["schemas"]["Subtopic"][];
        };
        /** TopicMeta */
        TopicMeta: {
            /** Id */
            id: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed" | "review";
            /** Perceived Difficulty */
            perceived_difficulty?: ("easy" | "ok" | "hard") | null;
            /**
             * Weak Points
             * @default []
             */
            weak_points: string[];
            /** Last Reviewed */
            last_reviewed?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_vault_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string | null;
                };
            };
        };
    };
    list_courses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseBundle"][];
                };
            };
        };
    };
    get_course: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_set: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
